"""Auto-generated convenience wrappers. See scripts/generate_call_wrappers.py."""
from __future__ import annotations

from eptr2.main import EPTR2

__all__ = [
    "get_ren_capacity",
    "get_ren_income",
    "get_ren_lic_cost",
    "get_ren_participant_list",
    "get_ren_pp_list",
    "get_ren_rt_gen",
    "get_ren_total_cost",
    "get_ren_uevm",
    "get_ren_ul_cost",
    "get_ren_ul_gen",
    "get_ren_unit_cost",
    "get_wind_forecast",
]

def get_ren_capacity(period: str, eptr: EPTR2 | None = None, **kwargs):
    """YEKDEM Installed Capacity / YEKDEM Kurulu Güç

    Category: YEKDEM

    EN (YEKDEM Installed Capacity):
        Total installed capacity of the generation facilities under renewables support mechanism. Licenced installation capacities are registered to EXIST, unlicenced installation capacities are fetched from the distribution corporations.

    TR (YEKDEM Kurulu Güç):
        YEKDEM kapsamındaki üretim tesislerinin kurulu güç miktarıdır. Lisanslı kurulu güç bilgileri EPİAŞ’a kayıtlı santraller olup, lisanssız kurulu güç bilgisi dağıtım şirketlerinden temin edilmektedir.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/installed-capacity
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-capacity", period=period, **kwargs)


def get_ren_income(start_date: str, end_date: str, eptr: EPTR2 | None = None, **kwargs):
    """YEKDEM Renewables Support Mechanism Income / YEK Geliri (YG)

    Category: YEKDEM

    EN (YEKDEM Renewables Support Mechanism Income):
        The data set regarding the Renewables Support Mechanism Income.

    TR (YEK Geliri (YG)):
        YEKDEM gelirine ilişkin veri setidir.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/renewables-support-mechanism-income
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-income", start_date=start_date, end_date=end_date, **kwargs)


def get_ren_lic_cost(start_date: str, end_date: str, eptr: EPTR2 | None = None, **kwargs):
    """YEKDEM Licensed Generation Feed-In Cost / YEK Bedeli (YEKBED)

    Category: YEKDEM

    EN (YEKDEM Licensed Generation Feed-In Cost):
        Hourly aggregate monetary value derived by the multiplication of feed-in energy quantity that is generated by licensed facilities under the renewables support mechanism and feed-in tariff prices. CBRT's fx buying rate of the date of energy feed-in is taken basis for TL currency conversion.

    TR (YEK Bedeli (YEKBED)):
        İlgili fatura dönemi için YEKDEM kapsamındaki lisanssız üretim santrallerine sahip katılımcılara ödenecek YEK bedelini (TL) ifade etmektedir.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/licensed-generation-feed-in-cost
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-lic-cost", start_date=start_date, end_date=end_date, **kwargs)


def get_ren_participant_list(year: str | int, eptr: EPTR2 | None = None, **kwargs):
    """YEKDEM Renewables Support Mechanism (RSM) Participant List / YEKDEM Katılımcı Listesi

    Category: YEKDEM

    EN (YEKDEM Renewables Support Mechanism (RSM) Participant List):
        It is a list of legal entities with a licensed power plant involved in the Renewable energy support mechanism within the relevant year. Since 2020, Previous year's production (Mwh) has not been published.

    TR (YEKDEM Katılımcı Listesi):
        İlgili yıl içerisinde Yenilenebilir Enerji Destekleme Mekanizmasına dahil olan lisanslı üretim santraline sahip tüzel kişilerin listesidir. 2020 yılından itibaren “Önceki Yıl gerçekleştirilen Üretim (MWh)” yayınlanmamaktadır.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/unit-cost
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-participant-list", year=year, **kwargs)


def get_ren_pp_list(period: str, eptr: EPTR2 | None = None, **kwargs):
    """Licensed Power Plant List / YEKDEM Santral Listesi

    Category: Listeleme

    EN (Licensed Power Plant List):
        Licensed Power Plant List

    TR (YEKDEM Santral Listesi):
        YEKDEM Santral Listesi

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/licensed-generation-amount/real-time-generation
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-pp-list", period=period, **kwargs)


def get_ren_rt_gen(start_date: str, end_date: str, pp_id: str | int | None = None, eptr: EPTR2 | None = None, **kwargs):
    """YEKDEM Real-Time Generation / YEKDEM Gerçek Zamanlı Üretim

    Category: YEKDEM

    EN (YEKDEM Real-Time Generation):
        The data set regarding hourly electricity generation quantity of licensed power plants within the scope of Renewable Energy Support Mechanism (YEKDEM)

    TR (YEKDEM Gerçek Zamanlı Üretim):
        Lisanslı YEKDEM santrallerine ait elektrik üretiminin kaynak bazında saatlik gösterimine ilişkin veri seti.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/licensed-generation-amount/real-time-generation
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-rt-gen", start_date=start_date, end_date=end_date, pp_id=pp_id, **kwargs)


def get_ren_total_cost(start_date: str, end_date: str, eptr: EPTR2 | None = None, **kwargs):
    """YEKDEM Total Cost (Licensed & License Exempt) / YEKDEM Toplam Gider (YEKTOB)

    Category: YEKDEM

    EN (YEKDEM Total Cost (Licensed & License Exempt)):
        The data set regarding the total renewable energy amount to be paid to licensed and unlicensed power plants within the scope of Renewable Energy Support Mechanism.

    TR (YEKDEM Toplam Gider (YEKTOB)):
        İlgili fatura dönemi için YEKDEM kapsamındaki hem lisanslı hem de lisanssız üretim santraline sahip katılımcılara ödenecek toplam YEK bedelini (TL) ifade eder.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/total-cost-licensed-license-exempt
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-total-cost", start_date=start_date, end_date=end_date, **kwargs)


def get_ren_uevm(start_date: str, end_date: str, eptr: EPTR2 | None = None, **kwargs):
    """YEKDEM Injection Quantity / YEKDEM Uzlaştırma Esas Veriş Miktarı (UEVM)

    Category: YEKDEM

    EN (YEKDEM Injection Quantity):
        The data set regarding hourly electricity injection quantity based on settlement of licensed power plants within the scope of Renewable Energy Support Mechanism (YEKDEM).

    TR (YEKDEM Uzlaştırma Esas Veriş Miktarı (UEVM)):
        YEKDEM kapsamındaki lisanslı santrallerin kaynak bazında saatlik olarak uzlaştırmaya esas veriş değerlerine ilişkin veri seti.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/licensed-generation-amount/injection-quantity
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-uevm", start_date=start_date, end_date=end_date, **kwargs)


def get_ren_ul_cost(start_date: str, end_date: str, eptr: EPTR2 | None = None, **kwargs):
    """YEKDEM License Exempt Generation Feed-In Cost / YEKDEM Lisanssız Üretim Bedeli

    Category: YEKDEM

    EN (YEKDEM License Exempt Generation Feed-In Cost):
        It represents the RES fee (TL) to be paid for owning unlicensed generation plants within the scope of YEKDEM for the relevant invoice period.

    TR (YEKDEM Lisanssız Üretim Bedeli):
        İlgili fatura dönemi için YEKDEM kapsamındaki lisanssız üretim santrallerine sahip katılımcılara ödenecek YEK bedelini (TL) ifade etmektedir.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/license-exempt-generation-feed-in-cost
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-ul-cost", start_date=start_date, end_date=end_date, **kwargs)


def get_ren_ul_gen(start_date: str, end_date: str, eptr: EPTR2 | None = None, **kwargs):
    """YEKDEM License Exempt Generation Feed-In Amount / YEKDEM Lisanssız Üretim Miktarı

    Category: YEKDEM

    EN (YEKDEM License Exempt Generation Feed-In Amount):
        These are the unlicensed data values of unlicensed power plants within the scope of YEKDEM for hourly reconciliation on a resource basis.

    TR (YEKDEM Lisanssız Üretim Miktarı):
        YEKDEM kapsamındaki lisanssız santrallerin kaynak bazında saatlik olarak uzlaştırmaya esas lisanssız veriş değerleridir.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/license-exempt-generation-feed-in-amount
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-ul-gen", start_date=start_date, end_date=end_date, **kwargs)


def get_ren_unit_cost(start_date: str, end_date: str, eptr: EPTR2 | None = None, **kwargs):
    """YEKDEM Unit Cost / YEKDEM Birim Maliyeti

    Category: YEKDEM

    EN (YEKDEM Unit Cost):
        It is the cost of Renewable Support Mechanism calculated per unit of energy supplied.Renewable Support Mechanism unit cost is published in versions for the relevant months.

    TR (YEKDEM Birim Maliyeti):
        Tedarik edilen birim enerji miktarı başına, hesaplanan YEKDEM maliyetidir. YEKDEM birim maliyeti ilgili aylar için versiyonlu olarak yayımlanmaktadır. Bir fatura döneminde, YEKDEM gelirinin YEK toplam bedelinden fazla olması durumunda, Yenilenebilir Enerji Kaynaklarının Belgelendirilmesi ve Desteklenmesine İlişkin Yönetmenliğin 13üncü maddesinin dördüncü fıkrası uyarınca hesaplama yapılmaktadır.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/unit-cost
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("ren-unit-cost", start_date=start_date, end_date=end_date, **kwargs)


def get_wind_forecast(start_date: str, end_date: str, eptr: EPTR2 | None = None, **kwargs):
    """WPP Generation and Forecast / RES Üretim ve Tahmin

    Category: Üretim

    EN (WPP Generation and Forecast):
        It is the total power production and estimation of WPPs that can be monitored throughout Turkey. The data is obtained from the wind power monitoring and estimation center. Data is updated every 10 minutes. Q5, Q25, Q75, Q95 refer to the prediction intervals. Band prediction intervals are created according to minimum and maximum risk scenarios.

    TR (RES Üretim ve Tahmin):
        Türkiye geneli izlenebilen RES’lerin toplam güç üretimi ve tahiminidir.Veriler rüzgar gücü izleme ve tahmin merkezinden temin edilmektedir. Veriler 10 dk arayla güncellenmektedir. Q5, Q25,Q75,Q95 tahmin aralıklarını ifade etmektedir. Band tahmin aralıkları minimum ve maksimum risk senaryolarına göre oluşturulmuştur.

    Reference: https://seffaflik.epias.com.tr/electricity/renewables-support-mechanism/wpp-generation-and-forecast
    """
    if eptr is None:
        eptr = EPTR2()
    return eptr.call("wind-forecast", start_date=start_date, end_date=end_date, **kwargs)

